language: python
python:
  - 2.7

install:
  - pip install -r requirements/base.txt --use-mirrors

script:
  - python manage.py test --settings=jtf.settings.test

before_script:
  - psql -c 'CREATE DATABASE jtf_test;' -U postgres
