language: python
python:
  - 2.7

env:
  - DJANGO=1.5.1
  - DJANGO=1.5.6
  - DJANGO=1.6.1
  - DJANGO=1.6.3

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements/dev.txt --use-mirrors

script:
  - python manage.py test --settings=jtf.settings.test

before_script:
  - psql -c 'CREATE DATABASE jtf_test;' -U postgres
